### ISSUE TITLE
Feature Request: Save All Objects Of A Base Class

### ISSUE THREAD

**Issue by Vegas-zzz** [code34/oo_pdw.Altis#3]
It would be amazing if we could save all objects listed under a baseclass if needed. This would prevent extremely long whitelists and blacklists. Typing the name of every car in the game would be very time consuming!

For example, function could be something like this:

```
	Function: ["setIncludingBaseclass",  _array] call _pdw;
	Set array of of objects type to whitelist
	
	Parameters: _array : array containing types of object ["Air", "Car"]

	Return : none

	------------------------------------------------------------------------------------------------

	Function: ["setExcludingBaseclass",  _array] call _pdw;
	Set array of of objects, dont have to be save. 
	
	Parameters: _array : array containing object 

Return : none
```

**Comment by code34** [comment]
yes, this is certainly possible but risks consuming resources. I would look at this point in 1 week.

**Comment by Vegas-zzz** [comment]
@code34 Thanks for your continued support. Your code is #splendid

**Comment by Vegas-zzz** [comment]
@code34 any update on this? Would be a huge advance in the system allowing much greater control over individual db files.

**Comment by code34** [comment]
just add tow functions on development version:

PUBLIC FUNCTION("array","setExcludingKindOf")
PUBLIC FUNCTION("array","setIncludingKindOf")

you can call them this way for example:
["setIncludingKindOf", ["Air"]] call _pdw;
["setExcludingKindOf", ["Air"]] call _pdw;

can you try it please and give me a feedback ?

**Comment by code34** [comment]
https://github.com/code34/oo_pdw.Altis/tree/develop

**Comment by Vegas** [comment]
OK, having some trouble with these functions. I can't get either of these to work. They just save everything across the whole map instead of Whitelisted objects and types. Both of these are not working:

// ==============================================================
_pdw = ["new", "inidbi"] call OO_PDW;
["setDbName", "21st_Wheeled"] call _pdw;

["setIncludingKindOf", ["Cars"]] call _pdw;
"saveObjects" call _pdw;

// ==============================================================

_pdw = ["new", "inidbi"] call OO_PDW;
["setDbName", "21st_Roadblocks"] call _pdw;

["setIncludingTypes", ["Land_CzechHedgehog_01_F"]] call _pdw;
"saveObjects" call _pdw;

// ==============================================================

Any ideas?

**Comment by Vegas-zzz** [comment]
Confirming everything is working as intended now. Thanks a lot for your help!
